/** @type {import('tailwindcss').Config} */
const colorVar = (name) => `rgb(var(${name}) / <alpha-value>)`;

module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: colorVar('--primary-rgb'),
          foreground: colorVar('--primary-foreground-rgb'),
          light: colorVar('--primary-light-rgb'),
          dark: colorVar('--primary-dark-rgb'),
          50: colorVar('--primary-50-rgb'),
          100: colorVar('--primary-100-rgb'),
          200: colorVar('--primary-200-rgb'),
          500: colorVar('--primary-500-rgb'),
          600: colorVar('--primary-600-rgb'),
          700: colorVar('--primary-700-rgb'),
          900: colorVar('--primary-900-rgb'),
        },
        secondary: {
          DEFAULT: colorVar('--secondary-rgb'),
          light: colorVar('--secondary-light-rgb'),
          dark: colorVar('--secondary-dark-rgb'),
        },
        accent: {
          DEFAULT: colorVar('--accent-rgb'),
          foreground: colorVar('--accent-foreground-rgb'),
          light: colorVar('--accent-light-rgb'),
          dark: colorVar('--accent-dark-rgb'),
        },
        background: {
          DEFAULT: colorVar('--background-rgb'),
          dark: colorVar('--background-dark-rgb'),
          card: colorVar('--background-card-rgb'),
          muted: colorVar('--background-muted-rgb'),
          elevated: colorVar('--background-elevated-rgb'),
        },
        foreground: {
          DEFAULT: colorVar('--foreground-rgb'),
          secondary: colorVar('--foreground-secondary-rgb'),
          muted: colorVar('--foreground-muted-rgb'),
          inverse: colorVar('--foreground-inverse-rgb'),
        },
        border: {
          DEFAULT: colorVar('--border-rgb'),
          focus: colorVar('--border-focus-rgb'),
          card: 'rgb(var(--border-card-rgb) / 0.12)',
        },
        success: colorVar('--success-rgb'),
        warning: colorVar('--warning-rgb'),
        error: colorVar('--error-rgb'),
        info: colorVar('--info-rgb'),
      },
      fontFamily: {
        heading: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['DM Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['DM Sans', 'sans-serif'],
      },
      fontSize: {
        'display-2xl': ['4.5rem', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-xl': ['3.75rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg': ['3rem', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.015em', fontWeight: '700' }],
        'display-sm': ['1.875rem', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        'heading-xl': ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        'heading-lg': ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.7', fontWeight: '400' }],
        'body-base': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        caption: ['0.75rem', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.05em' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '30': '7.5rem',
        '34': '8.5rem',
        '38': '9.5rem',
        '42': '10.5rem',
        '50': '12.5rem',
        '68': '17rem',
        '76': '19rem',
        '84': '21rem',
        '88': '22rem',
        '96': '24rem',
        '100': '25rem',
        '112': '28rem',
        '128': '32rem',
      },
      borderRadius: {
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        '4xl': '2.5rem',
        '5xl': '3rem',
      },
      boxShadow: {
        'sm-card': 'var(--shadow-sm)',
        'md-card': 'var(--shadow-md)',
        'lg-card': 'var(--shadow-lg)',
        'xl-card': 'var(--shadow-xl)',
        blue: 'var(--shadow-blue)',
        'blue-lg': 'var(--shadow-blue-lg)',
        'blue-sm': 'var(--shadow-blue-sm)',
        teal: 'var(--shadow-teal)',
        'inner-glow': 'inset 0 1px 0 rgba(255,255,255,0.1)',
        'dark-card': 'var(--shadow-dark-card)',
        'dark-xl': 'var(--shadow-dark-xl)',
      },
      backgroundImage: {
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-dark': 'var(--gradient-dark)',
        'gradient-hero': 'var(--gradient-hero)',
        'gradient-accent': 'var(--gradient-accent)',
        'gradient-card': 'var(--gradient-card)',
        'gradient-radial-blue': 'var(--gradient-radial-blue)',
        'gradient-radial-teal': 'var(--gradient-radial-teal)',
        'grid-pattern': 'var(--grid-pattern)',
        shimmer: 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.08) 50%, transparent 100%)',
      },
      backgroundSize: {
        grid: '60px 60px',
        shimmer: '200% auto',
      },
      animation: {
        float: 'float-up-down 6s ease-in-out infinite',
        'float-diagonal': 'float-diagonal 8s ease-in-out infinite',
        'float-slow': 'float-up-down 10s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 3s ease-in-out infinite',
        'spin-slow': 'spin-slow 20s linear infinite',
        'spin-reverse': 'spin-slow 15s linear infinite reverse',
        'fade-up': 'fade-up 0.7s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'slide-in-left': 'slide-in-left 0.6s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'slide-in-right': 'slide-in-right 0.6s cubic-bezier(0.34,1.56,0.64,1) forwards',
        shimmer: 'shimmer 2.5s linear infinite',
        'counter-up': 'counter-up 0.5s ease-out forwards',
        particle: 'particle-drift 4s ease-in-out infinite',
      },
      keyframes: {
        'float-up-down': {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(5deg)' },
        },
        'float-diagonal': {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '33%': { transform: 'translate(10px, -15px) rotate(3deg)' },
          '66%': { transform: 'translate(-8px, -10px) rotate(-2deg)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(37,99,235,0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(37,99,235,0.6), 0 0 80px rgba(14,165,233,0.2)' },
        },
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'fade-up': {
          from: { transform: 'translateY(30px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-left': {
          from: { transform: 'translateX(-40px)', opacity: '0' },
          to: { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-in-right': {
          from: { transform: 'translateX(40px)', opacity: '0' },
          to: { transform: 'translateX(0)', opacity: '1' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        'counter-up': {
          from: { transform: 'translateY(20px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        'particle-drift': {
          '0%': { transform: 'translateY(0) translateX(0)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { transform: 'translateY(-100px) translateX(20px)', opacity: '0' },
        },
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      maxWidth: {
        '8xl': '88rem',
        '9xl': '96rem',
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
    },
  },
  plugins: [],
};
